// Códigos de erro padronizados e organizados por contexto

export const ERROR_CODES = {
  // User Registration
  USER_REGISTRATION_EMAIL_EXISTS: "USER_REGISTRATION_EMAIL_EXISTS",
  USER_REGISTRATION_IMAGE_EMAIL_EXISTS: "USER_REGISTRATION_IMAGE_EMAIL_EXISTS",
  USER_REGISTRATION_VALIDATION_ERROR: "USER_REGISTRATION_VALIDATION_ERROR",

  // File Upload - Cloudinary (Base)
  CLOUDINARY_CONFIG_ERROR: "CLOUDINARY_CONFIG_ERROR",
  CLOUDINARY_UPLOAD_STREAM_ERROR: "CLOUDINARY_UPLOAD_STREAM_ERROR",
  CLOUDINARY_ENV_MISSING: "CLOUDINARY_ENV_MISSING",

  // File Upload - Contextualized (gerados automaticamente pelos métodos específicos)
  USER_AVATAR_CLOUDINARY_CONFIG_ERROR: "USER_AVATAR_CLOUDINARY_CONFIG_ERROR",
  USER_AVATAR_CLOUDINARY_UPLOAD_STREAM_ERROR:
    "USER_AVATAR_CLOUDINARY_UPLOAD_STREAM_ERROR",
  PROFILE_CLOUDINARY_CONFIG_ERROR: "PROFILE_CLOUDINARY_CONFIG_ERROR",
  PROFILE_CLOUDINARY_UPLOAD_STREAM_ERROR:
    "PROFILE_CLOUDINARY_UPLOAD_STREAM_ERROR",
  DOCUMENT_CLOUDINARY_CONFIG_ERROR: "DOCUMENT_CLOUDINARY_CONFIG_ERROR",
  DOCUMENT_CLOUDINARY_UPLOAD_STREAM_ERROR:
    "DOCUMENT_CLOUDINARY_UPLOAD_STREAM_ERROR",

  // Database
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  DATABASE_CONSTRAINT_ERROR: "DATABASE_CONSTRAINT_ERROR",

  // Validation
  VALIDATION_SCHEMA_ERROR: "VALIDATION_SCHEMA_ERROR",
  VALIDATION_REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",

  // Generic
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCodeType = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
